# Generated by Django 6.0.4 on 2026-04-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='one_time'),
        ),
    ]
